# Generated by Django 3.1.6 on 2021-02-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='modip@gmail.com', max_length=150),
            preserve_default=False,
        ),
    ]
