# Generated by Django 3.1.6 on 2021-02-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_person_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Employe',
        ),
        migrations.AlterModelTable(
            name='employe',
            table='employe',
        ),
    ]
