# Generated by Django 3.1.6 on 2021-02-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_auto_20210221_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='fonction',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
