# Generated by Django 3.1.6 on 2021-03-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_employe_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='telephone',
            field=models.CharField(default='string', max_length=30),
            preserve_default=False,
        ),
    ]
