# Generated by Django 3.1.6 on 2021-02-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='email',
            field=models.CharField(default='mo@gmail.com', max_length=30),
            preserve_default=False,
        ),
    ]
