# Generated by Django 3.1.6 on 2021-02-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeur', '0002_employeur_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeur',
            table='employeur',
        ),
    ]
